### ISSUE TITLE
Is XA Audio Ready?

### ISSUE THREAD

**Issue by MrQuetch** [ChenThread/candyk#1]
Hi, Adrian. This isn't really an issue. But, I hope you don't mind me asking... Is your implementation on XA audio complete or is it still a work-in-progress? Also, do you plan to release a binary (compiled and ready to use *.exe) at some point? I was thinking about emailing this to you directly - just figured I'd do it here instead. Hope you can get back to me. Thank you!

**Comment by asiekierka** [comment]
Yeah! XA/SPU audio is complete. No plans on releasing Windows binaries for the time being - the thing is unamintained and in need of refactors.
